# Promote to a DC in a new forest, DNS by default will be installed, SafeModeAdminPasswordIsAutoGenerated

#Get Domain name
    $domainname = Read-Host "Write your domain name [optional.]contoso.tld"

    #Valid domain pattern
    $pattern = "^[a-z0-9]+(\.[a-z0-9]+)*\.[a-z]+$"
    if (!($domainname -match $pattern))
    {
        Write-Error "Invalid Domain name: $domainname"
        Exit 1
    }

#Get NETBIOS name

    $netbiosname = Read-Host "Write your NETBIOS name CONTOSO"
    $pattern = "^[A-Z]$"
    if (!($netbiosname -match $pattern))
    {
        Write-Error "Invalid Domain name: $netbiosname"
        Exit 1
    }

#SafeModePassword Generation, because the subject doesnt ask for this as a parameter
$length = 24  # Specify the length of the password
$chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*_-+=?"  # Set of characters to use
$password = -join ((1..$length) | ForEach-Object { $chars | Get-Random })


Install-ADDSForest -DomainName $domainname -DomainNetbiosName $netbiosname -NoRebootOnCompletion -SafeModeAdministratorPassword (ConvertTo-SecureString -String $password  -AsPlainText -Force)


Write-Host "Your safemode password $password `t Keep it safely in case of an emergency" -ForegroundColor Red